name: sample_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    env:
      GREETING: Hello Everyone, Good Afternoon!
      LEARNING: learning GitHub-Actions
    environment: 
      name: PROD
    steps:
      - name: Printing statement 1
        run: echo "$GREETING"
      - name: Printing statement 2
        run: echo "$LEARNING"
      - name: Printing statement 2
        env:
          LEARNING: "Step-level override: Learning CI/CD"
        run: echo "$LEARNING"
  second-job:
    runs-on: ubuntu-24.04
    env:
      MSG3: Hello Everyone, Good Afternoon! This is the 3rd statement
    steps:
      - name: statement 3
        run: echo "$MSG3"
      - name: statement 4
        env:
          MSG4: This is 4th statement
        run: echo "$MSG4"
